### ISSUE TITLE
Problem names

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/OptimizationProblems.jl#106]
Some of the ADNLPModels have a name ending in "_autodiff" (e.g., arwhead), and others not (e.g., palmer1c). I don't think it's necessary to append "_autodiff" to the name; we'll know from the NLPModel type what kind of model it is. We should just use the plain name everywhere.

**Comment by tmigot** [comment]
thanks for catching this and the suggestion.
Closed via #107
