### ISSUE TITLE
Fixed `n` in `rosenbrock`

### ISSUE THREAD

**Issue by paraynaud** [JuliaSmoothOptimizers/OptimizationProblems.jl#208]
@dpo, @tmigot, I tried to call 
```julia
n=10
PureJuMP.rosenbrock(;n)
```
and I ended up with a problem with 2 variables:
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/8a219602a1357eac7ed84c632ec93204ecec8820/src/PureJuMP/genrose.jl#L77

I think `n=2` could be removed in the line
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/8a219602a1357eac7ed84c632ec93204ecec8820/src/ADNLPProblems/genrose.jl#L16

I can open a PR replacing both lines with :
```julia
 rosenbrock(args...; kwargs...) = genrose(; kwargs...) 
```
if you are ok with this change.

**Comment by tmigot** [comment]
Not sure, I see the problem here.
`rosenbrock` is the 2-variable version of `genrose`, so it is not surprising that it is not scalable.

**Comment by paraynaud** [comment]
Okay, you can note that:
```julia
n=10
ADNLPProblems.rosenbrock(;n)
```
creates a 10-variable problem.

**Comment by tmigot** [comment]
Ah ok, I get it. In `rosenbrock` we need to remove any other `n` keyword so that the `n=2` is not overwritten. Would that work?

**Comment by paraynaud** [comment]
If you plan to get a 2-variable problem the PureJuMP version works, even if I'm not sur how `default_nvar` works and how it is related to `n=2` in 
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/8a219602a1357eac7ed84c632ec93204ecec8820/src/PureJuMP/genrose.jl#L77

However, we should remove the `kwargs...` in the ADNLPProblems version 
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/8a219602a1357eac7ed84c632ec93204ecec8820/src/ADNLPProblems/genrose.jl#L16
and it should behave as PureJuMP.

**Comment by tmigot** [comment]
`default_nvar` is a constant fixed at 100.

I don't like the idea of removing the `kwargs` for the `ADNLPProblems` because we use them to change the backend.

What about this?
```
rosenbrock(args...; kwargs...) = genrose(args..., n = 2; delete!(Dict(kwargs), :n)...) 
```

**Comment by paraynaud** [comment]
> I don't like the idea of removing the kwargs for the ADNLPProblems because we use them to change the backend.

I get it.

```julia
rosenbrock(args...; kwargs...) = genrose(args..., n = 2; delete!(Dict(kwargs), :n)...) 
```
should work.
Is there an advantage over 
```julia
rosenbrock(args...; kwargs...) = genrose(args...; n = 2, kwargs...) 
```
?

For myself, if there is an argument `n`, for example `genrose(n=2;...)`, and no optionnal argument `n`, similarly to:
`rosenbrock(args...; kwargs...) = genrose(n = 2)`, will `n=2` sets the `n` optionnal argument `genrose(;n)` to `2`?

**Comment by tmigot** [comment]
> > I don't like the idea of removing the kwargs for the ADNLPProblems because we use them to change the backend.
> 
> I get it.
> 
> ```julia
> rosenbrock(args...; kwargs...) = genrose(args..., n = 2; delete!(Dict(kwargs), :n)...) 
> ```
> 
> should work. Is there an advantage over
> 
> ```julia
> rosenbrock(args...; kwargs...) = genrose(args...; n = 2, kwargs...) 
> ```
> 
> ?

The advantage is that `delete!(Dict(kwargs), :n)...` will ensure that no other `n` is specified in `kwargs` overwriting the `n=2`.

> For myself, if there is an argument `n`, for example `genrose(n=2;...)`, and no optionnal argument `n`, similarly to: `rosenbrock(args...; kwargs...) = genrose(n = 2)`, will `n=2` sets the `n` optionnal argument `genrose(;n)` to `2`?

I tried to replicate the situation there:
```
function test(n=100; kwargs...) return n end
function test2(args...; kwargs...) return test(n=2; kwargs...) end
test2(n = 2) # return 100
```
It's always a bit tricky!
