### ISSUE TITLE
setobjectivesense not defined

### ISSUE THREAD

**Issue by Goysa2** [JuliaSmoothOptimizers/OptimizationProblems.jl#24]
I just updated a lot of packages, because I hadn't used Julia in a while. 
Now I cannot "define" a problem the way I used to. 
I do 
`using Optimize, NLPModels, OptimizationProblems`
`prob = MathProgNLPModel(arwhead())`

And I get the following error: 
`ERROR: UndefVarError: setobjectivesense not defined` 

This error is from the package JuMP. I am not exactly sure how to fix it, since so many of the packages I used are now tweaked.

**Comment by abelsiqueira** [comment]
I think your `OptimizationProblems` is not updated. Try `Pkg.checkout("OptimizationProblems")`.

**Comment by Goysa2** [comment]
When I do `Pkg.checkout("OptimizationProblems")` I get the following:
```
INFO: Checking out OptimizationProblems master...
INFO: Pulling OptimizationProblems latest master...
INFO: No packages to install, update or remove
```

And I get the same error as before when I define "prob". I am quite confused.

**Comment by dpo** [comment]
The error may be due to the new version of MathProgBase. What versions of JuMP and MPB are you using?

**Comment by abelsiqueira** [comment]
Are you on Julia 0.6?

**Comment by Goysa2** [comment]
Yes, Julia 0.6.0 and I have JuMP 0.17.1 and MathProgBase 0.7.0

**Comment by abelsiqueira** [comment]
I'm on JuMP 0.18, can you try to update?

**Comment by dpo** [comment]
I thought we only supported JuMP 0.15.

**Comment by Goysa2** [comment]
The problem was fixed by updating to JuMP 0.18! 
I just thought I'd mention that I had to use Pkg.free("JuMP") in order to update to 0.18 and Pkg.update("JuMP") didn't do anything. Thank you very much!!

**Comment by abelsiqueira** [comment]
This is odd indeed, the change to the new JuMP syntax was JuMP 0.15, almost one year ago, so it must have been something else.
When you freed JuMP, any other packages updated?

**Comment by dpo** [comment]
OK. Actually I'm also using 0.18.

**Comment by Goysa2** [comment]
Here are the message I received : 
![free-jump](https://user-images.githubusercontent.com/22686485/34992643-d2674cf4-fa9b-11e7-9bd4-3e34eb772490.png)

**Comment by abelsiqueira** [comment]
I downgraded to 0.17.1 and it worked, so it must've been something else. It's resolved, however, so closing.
