### ISSUE TITLE
New nonlinear least-squares problem

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/OptimizationProblems.jl#25]
![photo on 2018-02-21 at 17 58](https://user-images.githubusercontent.com/38760/36493932-055b4366-1731-11e8-9a78-b4fa4190f5c6.jpg)

**Comment by Xx-fractale-xX** [comment]
[NZF1.jl.zip](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/files/1957007/NZF1.jl.zip)

**Comment by dpo** [comment]
Did you mean to submit a pull request?

**Comment by dpo** [comment]
Closed by #26.
