### ISSUE TITLE
Use NLPJuMPModels

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/OptimizationProblems.jl#29]

**Comment by Xx-fractale-xX** [comment]
@abelsiqueira, can I help you with the upgrade of packages `OptimizationProblems` and `NLSProblems` to Julia 0.7?

**Comment by abelsiqueira** [comment]
Thanks for offering @Xx-fractale-xX, but `JuMP` is not on 0.7 yet. They are updating `JuMP` to use the new `MathOptInterface`, then we'll wave to update this `NLPJuMPModels` to use that, and only then `OptimizationProblems` and `NLSProblems`, unfortunately.
As for updating this to use `NLPJuMPModels`, we need `NLPModels` 0.5.0, which needs `AmplNLReader` (https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/50) to pass on Linux. If you have the time, you could help us investigate, thanks.

**Comment by abelsiqueira** [comment]
My mistake, this doesn't use `NLPModels`. Should keep a look out for JuMP 18.3 though.
