### ISSUE TITLE
Add Breakage.yml workflow with JSOSuite

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/OptimizationProblems.jl#330]
Version 0.7.4 was a breaking change (changed the API) and so it broke JSOSuite.
This could have been caught if we had a breakage workflow and ran that before releasing 0.7.4

**Comment by tmigot** [comment]
Sorry @abelsiqueira we realized this too late https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/commit/3054d7c241d5e2ccf194e92baf554b288ef36742 . Do you think we should undo 0.7.4 and make a 0.8.0 instead?

**Comment by abelsiqueira** [comment]
We could revert, release 0.7.5, apply the change again and release 0.8.0
