### ISSUE TITLE
Fix: `clplatea` small dimension issue

### ISSUE THREAD

**Issue by danphenderson** [JuliaSmoothOptimizers/OptimizationProblems.jl#355]
Currently, ` prob = ADNLPProblems.clplatea(n=N)` fails for all $N < 9$ as a result of this sum in it's definition:

```julia
           sum(
             sum(
               1 // 2 * (x[i + (j - 1) * p] - x[i - 1 + (j - 1) * p])^2 +
               hp2 * (x[i + (j - 1) * p] - x[i - 1 + (j - 1) * p])^4 for j = 2:p
             ) for i = 3:p
           )
```

Where $p$ is defined to be $p = floor(Int, sqrt(n))$. So, $N$ must be greater than  $8$ for `sum( .... for i=3:p)` to be over a non-empty collection.

Suggested fixes:
- Update the warning statement and properly adjust the number of variables to be 9 or greater.
- Or, depending on the province and if it makes sense, we may modify the above sum as `sum((... for i = 3:p); init=0.0)`; but then an issue would arise for $N < 4$ if similar action isn't taken to modify the two other sums in `clplatea`'s definition.

**Comment by danphenderson** [comment]
Similar issues arise for `clplateb` and `clplatec`.

**Comment by tmigot** [comment]
Hi @danphenderson ! Thanks for the issue.
We fixed a couple similar recently, so I am not surprised. Since, you already analyzed the problem could you open a PR to fix this issue?

**Comment by tmigot** [comment]
Sorry, I didn't read the whole message^^
The solution adjust the number of variables to be 9 or greater is good I think since it's really a corner case and using "small" dimension should mainly be for testing and debugging.
