### ISSUE TITLE
Update names of `errinros_mod`, `chnrosnb_mod` and `fletcbv3_mod`?

### ISSUE THREAD

**Issue by danphenderson** [JuliaSmoothOptimizers/OptimizationProblems.jl#356]
The current names of these ADNLPModels are `errinros`, `chnrosnb` and `fletcbv3`; respectively.

In my use case, I am instantiating a set of ADNLPModels from a list of their names; but I run into issues with these models as their names do not correspond to the name of the file in the source code.

A fix would be to update these model's names to `errinros_mod`, `chnrosnb_mod` and `fletcbv3_mod`.

**Comment by danphenderson** [comment]
Also, `indef_mod`.

**Comment by tmigot** [comment]
Thanks @danphenderson for the issue. You are right, bwe should modify the problems' names.

For errinros_mod:
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/f563bb655758d816eecff69eeddba7a7c866e267/src/ADNLPProblems/errinros_mod.jl#L21
and also the NLS variant:
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/f563bb655758d816eecff69eeddba7a7c866e267/src/ADNLPProblems/errinros_mod.jl#L40

This could also be tested, probably here:
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/f563bb655758d816eecff69eeddba7a7c866e267/test/runtests.jl#L29
`@test nlp_ad.meta.name == String(pb)`

strangely enough the name was correct in the dataframe describing the problems
https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/f563bb655758d816eecff69eeddba7a7c866e267/src/Meta/errinros_mod.jl#L7

@danphenderson Would you be interested in opening a PR to fix this?

**Comment by danphenderson** [comment]
@tmigot, thanks for the additional instructions - PR submitted.
