### ISSUE TITLE
Problems and check lists

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/OptimizationProblems.jl#52]
I was wondering if there was a checklist of the problem sets used in `OptimizationProblems.jl`?
I noticed that most (all?) of the CUTEr/st, Schittkowski collection, and Moré-Garbow-Hillstrom have been implemented.

Having such a list would probably help to suggest new ones.

Along the same line, what would you think about a function that verifies if a problem is already on the list (maybe up to a constant scaling)? It would help to review new ones.

**Comment by dpo** [comment]
Yes, a list would be great. We've been mostly working out of one of the tech reports by Luksan & Vlcek. We're not anywhere near having all CUTEst problems; there are > 1000 of them. Also, there are a bunch of problems with just one variable that I think should be removed from here.

> what would you think about a function that verifies if a problem is already on the list (maybe up to a constant scaling)? It would help to review new ones.

How would that work? Random sampling?

**Comment by tmigot** [comment]
I thought we could use the `Projects` feature in Github to keep track of each list of problems (with a link and a date) and to see what is already done and in review.

Yes, mainly random sampling, something like:
- check the number of variables, number of constraints;
- randomly evaluate the objective and constraint functions;
- if we had `!=0` values in the previous step, check also if there is a constant scaling.
It is a bit naive but should be an helpful first step for reviewing even if checking only 2-3 points.

**Comment by abelsiqueira** [comment]
I like the `Projects` idea. Do you permission to set it up? I personally use issues and ZenHub to keep a board, so I don't remember how `Projects` work.

About checking whether a problem is already here, one very useful thing that we couldn't make yet is something related to #3, i.e., a way to select problems.

**Comment by tmigot** [comment]
> I like the `Projects` idea. Do you permission to set it up? I personally use issues and ZenHub to keep a board, so I don't remember how `Projects` work.

The potential drawback of Projects is that one needs permission to create one. Maybe `issues` are actually sufficient.

> About checking whether a problem is already here, one very useful thing that we couldn't make yet is something related to #3, i.e., a way to select problems.

That would be great indeed.

**Comment by dpo** [comment]
> Yes, mainly random sampling

It's difficult because problems come in variable sizes. I think adding new problems and selecting problems conveniently should take precedence on checking whether a problem is already in there.

**Comment by tmigot** [comment]
There is now a JSO-project for this. See for instance #111
