### ISSUE TITLE
New problems for students

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/OptimizationProblems.jl#7]
I'm gonna have some students create new problems here. I'm thinking selected problems from Hock-Schittkowski. Do you have a different suggestion?

**Comment by abelsiqueira** [comment]
@dpo

**Comment by dpo** [comment]
Great idea. We started adding the problems from [Luksan and Vlcek](http://www.cs.cas.cz/matonoha/download/V1081.pdf). It would be great to finish those first. They are unconstrained and come in many dimensions.

After that, the unconstrained and bound-constrained Hock-Schittkowski problems would be a good addition.

There's also the [Moré-Garbow-Hillström collection](http://dx.doi.org/10.1145/355934.355936) of unconstrained problems. They are all nonlinear least squares.

**Comment by Xx-fractale-xX** [comment]
I found [More Test Examples for Nonlinear Programming Codes](https://www.springer.com/gb/book/9783540171829), which is a supplement of the test problem collection published by Hock and Schittkowski : [Test Examples for Nonlinear Programming Codes](https://www.springer.com/us/book/9783540105619).

**Comment by tmigot** [comment]
There is no a project on this repo for this, and the various suggestions have been dispatched to different issues.
