### ISSUE TITLE
Fix unit tests for `hs61`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/OptimizationProblems.jl#72]
Since PR #69 , the JuMP models have an ADNLPModels translation, and we check the compatibility in the unit tests using [NLPModelsJuMP.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl).
There is an issue with `hs61` (see [runtests.jl L16](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/c562568f35b52fd017128f8a1c5f433c01a201ef/test/runtests.jl#L16)) because MathOptNLPModel is not working in this situation [see #84 in NLPModelsJuMP.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/issues/84).

**Comment by dpo** [comment]
what's the issue exactly? I don't see `@NLconstraint` in hs61.

**Comment by tmigot** [comment]
Fixing [Issue 50 in NLPModelsJuMP.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/issues/50) would solve this issue.

**Comment by amontoison** [comment]
I can work on the support on quadratic constraints in `NLPModelsJuMP.jl` if we agree on the storage for them.
